CREATE ROLE R_CUSTOMER;
GRANT SELECT
ON ARTIST TO R_CUSTOMER;
GRANT SELECT
ON TRADE TO R_CUSTOMER;
GRANT SELECT
ON GALLERY TO R_CUSTOMER;
GRANT SELECT
ON EXHIBITION TO R_CUSTOMER;
GRANT SELECT
ON EXB_ARTIST TO R_CUSTOMER;
GRANT SELECT, UPDATE
ON CUSTOMER TO R_CUSTOMER;

CREATE ROLE R_ARTIST;
GRANT SELECT, UPDATE, INSERT
ON ARTIST TO R_ARTIST;
GRANT SELECT
ON TRADE TO R_ARTIST;
GRANT SELECT
ON GALLERY TO R_ARTIST;
GRANT SELECT
ON EXHIBITION TO R_ARTIST;
GRANT SELECT
ON EXB_ARTIST TO R_ARTIST;

CREATE ROLE R_GALLERY;
GRANT SELECT, UPDATE, INSERT, DELETE
ON ARTIST TO R_GALLERY;
GRANT SELECT, UPDATE, INSERT, DELETE
ON TRADE TO R_GALLERY;
GRANT SELECT, UPDATE
ON GALLERY TO R_GALLERY;
GRANT SELECT, UPDATE, INSERT, DELETE
ON EXHIBITION TO R_GALLERY;
GRANT SELECT, UPDATE, INSERT, DELETE
ON EXB_ARTIST TO R_GALLERY;

CREATE ROLE R_EXHIBITION;
GRANT SELECT
ON ARTIST TO R_EXHIBITION;
GRANT SELECT
ON GALLERY TO R_EXHIBITION;
GRANT SELECT, UPDATE, INSERT, DELETE
ON EXHIBITION TO R_EXHIBITION;
GRANT SELECT, UPDATE, INSERT, DELETE
ON EXB_ARTIST TO R_EXHIBITION;

CREATE ROLE R_SYSTEM;
GRANT SELECT, UPDATE, INSERT, DELETE
ON GALLERY TO R_SYSTEM;
