-- 创建数据库角色
use AG
go
CREATE ROLE R_MANAGER;
CREATE ROLE R_CUSTOMER;
CREATE ROLE R_ARTIST;
CREATE ROLE R_GALLERY;
go

-- 为系统管理员分配权限
GRANT ALL PRIVILEGES
ON ARTIST TO R_MANAGER;
GRANT ALL PRIVILEGES
ON CUSTOMER TO R_MANAGER;
GRANT ALL PRIVILEGES
ON GALLERY TO R_MANAGER;
GRANT ALL PRIVILEGES
ON EXHIBITION TO R_MANAGER;
GRANT ALL PRIVILEGES
ON EXB_ARTIST TO R_MANAGER;
GRANT SELECT
ON CUST_RECORD TO R_MANAGER;
GRANT ALL PRIVILEGES
ON TRADE TO R_MANAGER;
GRANT ALL PRIVILEGES
ON ARTWORK TO R_MANAGER;

-- 为角色顾客分配权限
GRANT SELECT
ON ARTIST TO R_CUSTOMER;
GRANT SELECT
ON TRADE TO R_CUSTOMER;
GRANT SELECT
ON GALLERY TO R_CUSTOMER;
GRANT SELECT
ON EXHIBITION TO R_CUSTOMER;
GRANT SELECT
ON EXB_ARTIST TO R_CUSTOMER;
GRANT SELECT, UPDATE(CNAME,CADDRESS,CDOB,CPHONE)
ON CUSTOMER TO R_CUSTOMER;
GRANT SELECT
ON ARTWORK TO R_CUSTOMER;
GRANT SELECT, UPDATE(SATISFACTION)
ON CUST_RECORD TO R_CUSTOMER;
go

-- 为艺术家分配权限
GRANT SELECT, UPDATE(ARTISTNAME,ARTISTBP,ARTISTSTYLE,GID)
ON ARTIST TO R_ARTIST;
GRANT SELECT
ON TRADE TO  R_ARTIST;
GRANT SELECT
ON GALLERY TO R_ARTIST;
GRANT SELECT
ON EXHIBITION TO  R_ARTIST;
GRANT SELECT
ON EXB_ARTIST TO  R_ARTIST;
GRANT SELECT
ON ARTWORK TO  R_ARTIST;
GRANT SELECT
ON CUST_RECORD TO  R_ARTIST;
go

-- 为画廊管理员分配权限
GRANT SELECT, UPDATE(GID)
ON ARTIST TO R_GALLERY;
GRANT SELECT
ON TRADE TO  R_GALLERY;
GRANT SELECT
ON GALLERY TO R_GALLERY;
GRANT SELECT, UPDATE(ESTARTDATE,ENAME,EENDDATE), INSERT
ON EXHIBITION TO  R_GALLERY;
GRANT SELECT, INSERT, DELETE
ON EXB_ARTIST TO  R_GALLERY;
GRANT SELECT, INSERT, UPDATE(ARTTITLE,ARTTYPE,ARTYEAR,ARTPRICE,ARTSTATUS,GID,EID)
ON ARTWORK TO  R_GALLERY;
GRANT SELECT, INSERT
ON CUST_RECORD TO  R_GALLERY;
go
