--创建基本表
--画廊
CREATE TABLE GALLERY
(
    GID VARCHAR(10) PRIMARY KEY,
    GNAME VARCHAR(20),
    GLOCATION VARCHAR(40)
);

--展览
CREATE TABLE EXHIBITION
(
    EID VARCHAR(10) PRIMARY KEY,
    ESTARTDATE DATE,
    ENAME VARCHAR(20),
    EENDDATE DATE,
    GID VARCHAR(10),
    FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE SET NULL
);

--顾客
CREATE TABLE CUSTOMER
(
    CID VARCHAR(10) PRIMARY KEY,
    CNAME VARCHAR(20),
    CADDRESS VARCHAR(40),
    CDOB DATE,
    CPHONE VARCHAR(11)
);

--艺术家
CREATE TABLE ARTIST
(
    ARTISTID VARCHAR(10) PRIMARY KEY,
    ARTISTNAME VARCHAR(20),
    ARTISTBP VARCHAR(40),
    ARTISTSTYLE VARCHAR(20),
    GID VARCHAR(10),
	FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE SET NULL
);

--艺术品
CREATE TABLE ARTWORK
(
    ARTID VARCHAR(10) PRIMARY KEY,
    ARTTITLE VARCHAR(20),
    ARTTYPE VARCHAR(10),
    ARTYEAR VARCHAR(4),
    ARTPRICE MONEY,
    ARTSTATUS VARCHAR(10) DEFAULT('正常'),
    ARTISTID VARCHAR(10),
    GID VARCHAR(10),
    EID VARCHAR(10),
    FOREIGN KEY(ARTISTID) REFERENCES ARTIST(ARTISTID),
    FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE SET NULL,
    FOREIGN KEY(EID) REFERENCES EXHIBITION(EID),
    CHECK(ARTSTATUS IN ('正常','展示中','已出售')),--艺术品状态仅能取三者之一
    CHECK(ARTPRICE > 0)
);

--参展满意度调查
CREATE TABLE CUST_RECORD
(
    EID VARCHAR(10),
    CID VARCHAR(10),
    SATISFACTION SMALLINT,
    PRIMARY KEY(EID,CID),
    FOREIGN KEY(EID) REFERENCES EXHIBITION(EID),
    FOREIGN KEY(CID) REFERENCES CUSTOMER(CID),
    CHECK(SATISFACTION>0 AND SATISFACTION<=5)
);

--参展艺术家
CREATE TABLE EXB_ARTIST
(
    EID VARCHAR(10),
    ARTISTID VARCHAR(10),
    PRIMARY KEY(EID,ARTISTID),
    FOREIGN KEY(EID) REFERENCES EXHIBITION(EID),
    FOREIGN KEY(ARTISTID) REFERENCES ARTIST(ARTISTID)
);

--交易记录
CREATE TABLE TRADE
(
    TRADEID VARCHAR(10) PRIMARY KEY,
    CID VARCHAR(10),
    ARTID VARCHAR(10),
    TRADEDATE DATE,
    TRADESTATUS VARCHAR(10) DEFAULT('建立'),
    GID VARCHAR(10), --使画廊管理人员能够根据GID快速查询自己画廊交易信息
    FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) ON DELETE SET NULL,
    FOREIGN KEY(GID) REFERENCES GALLERY(GID) ON DELETE SET NULL,
    FOREIGN KEY(ARTID) REFERENCES ARTWORK(ARTID) ON DELETE SET NULL,
    CHECK(TRADESTATUS IN ('建立','运输中','已完成','取消'))
);
go
